### ISSUE TITLE
Prompt user to overwrite unbox when `path already exist`

### ISSUE THREAD

**Issue by DenisCarriere** [liquidapps-io/zeus-cmd#7]
Whenever a box is already installed or the unboxing failed mid process, it would be nice to have zeus ask if you want to "overwrite" existing box with new box.

That way you can quickly update/upgrade/replace existing boxes with the latest release.

```
$ zeus unbox dapp-services-deploy
Error: path already exists
```

- [ ] Remove throwing error `path already exist`
- [ ] Prompt user to "overwrite" box if path already exist

**Comment by NatPDeveloper** [comment]
We will take this into consideration Denis, thank you for posting!

**Comment by bitcoiners** [comment]
I am having same issue.
```
zeus unbox helloworld
Error: path already exists

```

how to overwrite?

**Comment by NatPDeveloper** [comment]
You can just do

```sh
rm -rf helloworld/
```

**Comment by bitcoiners** [comment]
thanks26.05.2019, 11:45, "Nat" <notifications@github.com>:You can just do
rm -rf helloworld/
