### ISSUE TITLE
invalid signature unboxing

### ISSUE THREAD

**Issue by bitcoiners** [liquidapps-io/zeus-cmd#8]
Getting an error unboxing packages on a dsp cluster running on aws

```
zeus --version
1.8.1051


 zeus unbox helloworld
⚙️Unboxing: helloworld
Error: invalid signature: 0x4f44213c
    at /dapp-cluster-k8s/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

reported this problem here too: 
https://github.com/liquidapps-io/vgrab/issues/1

**Comment by NatPDeveloper** [comment]
Hey it sounds like we're figuring this out in vgrab, but usually invalid signature means the IPFS pointer is dead.  Zeus looks at the mapping.js file to unboxing files.
